#import time
#
#
#print("                              .WWWWWWWWWWWWW.")
#print("                           .WWWWWWWWWWWWWWWWWWW.")
#print("                         .WWWWWWWWWWWWWWWWWWWWWWW.")
#print("                       .WWWWWWWWWWWWWWWWWWWWWWWWWWW.")
#print("                     .WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.")
#print("                    .WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.")
#print("                   .WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.")
#print("                  .WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.")
#print("                 .WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW")
#print("                .WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW")
#print("                WWWWWWWWWWWWWWWWWWWWWWWWWWWWW WWWWWWWWWWW.")
#print("               .WWWWWWWWWWWWWWWWWWWWWWWWWWW W WWWWWWWWWWSW")
#print("               WWWWWWWWWWWWWWWWWWWWWWWWWWWWW WWWWWWWWWWWWW")
#print("              .WWWWWWWWWWWWWWWWWWWWWWWWW...WWWWWWWWWWWWWWW")
#print("             .WWWWWWWWWWWWWW.WWWWW.WWWWW.WWWWWWWW...WWWWWW")
#print("             .WWWWWWWWWWWWWW...WWWWW        WWWWW...WWWWWW")
#print("            .WWWWWWWWWWWWWWW.:.:.WW MM   WWWWWW...WWWWWWW'")
#print("            WWWWWWWWWWWWWWWM..:.:  ::MM        ..::WWWWWW")
#print("           .WWWWWWWWWWWWWWWM.:.:. ..MMM       ..::WWWWWWW")
#print("           WWWWWWWWWWWWWWWWWM.:.: .:MMMMMM :   ::WWWWWWWW")
#print("           'WWWWWWWWWWWWWWWWM :::.:           :.WWWWWWWWW.")
#print("            'WWWWWWWWWWWWWWWWM:.:. MMMMMMMMM: :.WWWW WWWWW.")
#print("             'WWWWWWWWWWWWWWWM.:.:  MMMMMMM  .MWWWWW WWWWW.")
#print("              'WWWWWWWWWWWWWWWWW:.:::.:.:. :.:.WWW  WWWWWW.")
#print("               'WWWWWWWWWWWWWWWWM:.::----.: MWWWWWWWWWWWWWW")
#print("               .WWWWWWWWWWWWWWW  MM :::  MMM WWW  WWWWWWWWW")
#print("            .WWWWWWWWWWWWWWWWWWW   MMMMMM   WWW  :WWWWWWWWW.")
#print("          .WWWWWWWWWWWWWWWWWWW  MM:.:        WW  :WWWWWWWWWW")
#print("         .WWWWWWWWWWWWWWWWWWWW MMM:.:.:.: :::  .WWWWWWW WW'")
#print("         .WWWWWWWWWWWWWWWWWWWW  MM.:.:.:  ::W :WWWWWWWWWW'")
#print("         .WWW:::        WWWWWW MMMM.:.::  ::WWWWW::WW W'")
#print("         'WW:::::      W     :.:  ::        WWWWWWWW  W")
#print("          ':::::::     WW  WWWWWWW:.:.:      WWWWWWW W W.")
#print("            ::::::::    WWW WWWWWW:.:.:.:::    WWWWW  WW W")
#print("           :::::::::    WWWW:::::::  : WWWWWW : WWWWW WW  W.")
#print("          .::::::::     WWWWWWWW   .:::::::::  :  WWWWWW W  W.")
#print("          :::::::::       WWW      ::::::::   ::  WWWWWW WWWW.")
#print("          :::::::::                .:::::::    ::  WWWWWW    .")
#print("         .::::::::.:                 .:::::    ::::: W WWWWWW.")
#print("         ::::::::::.:                .:::::      :::WWW W  WWW")
#print("         ::::::::::.:      .:         .::::           WWW")
#print("         ::M::::::.:.     :M...        ..::           . .")
#print("         ::M:::::::..    .:M:..             :          .")
#print("         ::M::::::::.    MM:M..            .:..        ::")
#print("         ::M:::::::.:.   M:M:.:.            ::..        ::")
#print("         ::M::::::.:..  .MM:M:.:.            :...        :")
#print("         ::M:::::.:.:. .:M:MM.:...            :...       :")
#print("         :M::::.:.:.:. MMM:.:.:..             :...       :.")
#print("          M:::::::.:.. MMM:M:.MM..        :::  :..       .:.")
#print("          M::::::.:.:. MM:.:.:.M:M..   ..... :..          .:.")
#print("          :::::::.:..  MM:.::::M:M:M:::::MM: : ..         .:.")
#print("          M::::::.:.:. MM::.:M:M:M:M:::::::: :  ...        .:.")
#print("          M:::::::.:.. MM:M:M:M:.:.:.:.:    :   ::::       ::.")
#print("          M::::::.:.:.  MMM:M.::.:.:.:.:. ::' :  :::::   :::'")
#print("          M:::::::.::.  MMMMM:M:MMMMMMMMMM    :  ::::::   ::")
#print("          M:::::::..:.  MMMM:M:M:M:MMMM       :  :::::::-'")
#print("          M:::::::.:.   MMMMM:M               : :::::::'")
#print("          M::::::::.:   MMMM:::.              :/:-'")
#print("          M:::::::.:.   MMM:M:               :/ :")
#print("          M::::::::.:   MMM:                 /  :")
#print("         .M:::::::.:.   'MMMM               /   :")
#print("         :M::::::::.:    :MMM              /    :")
#print("        .MM::::::::::.    :                ::.  :")
#print("        :.MM:::::::::..    :              /::.  :")
#print("       .M::MM::::::::::::   :             M::.  :")
#print("       :::::MM::::::::::     :           ::::.  :")
#print("       .M::::MM::::::::::.    :        MM::::.: /")
#print("      .::::::::MM::::::::::    :       MM:::   :")
#print("     .M:::::::::MMM::::::::     :        M::.  :")
#print("    .M:::::::::::MMM:::::::::    :       M::.  /")
#print("   .M:::::.::::::::MM::::::::::   :      M::. :")
#print("  .M::::::::.::::::::MMM:::::::::  :     M:::./")
#print(" .M:::::::.:.:::::::::MMM::::::::   :   M::..:")
#print(".M:::.:::::::::::::::MMMM::::::::::  : M:::. :")
#time.sleep(1)
#print("M:::::::::::::::::::::MMMMMM::::::::  'M:::. :")
#print("M::.::.:::::.:::::::::::MMMMMMM::::::   MMM  .")
#print("M:.::::::::::::.:.:.:.:.:.MMMMM::::::::   M  :")
#print("M:.:.:.::::::::..:.:.:.:....     M::::::   '::")
#print("M::.:.:.:::::::.:.:.:.:..:.        M::::::   :")
#print("M:::.:.:::::::::.:.:.:..:.. .         M:::MMM :::")
#print("M:.:.:.:::::::::::.:.:.:..... ..        :::MM  :::::::.")
#print("M::.:.:.:::::::::::::.:.:...... .        MM:MMM  :::::::::.")
#print("M:.:.:.:.:.::.::::::::.:.:....... .         ::::MM: M  ::::.:.:")
#print("'M::.:.:.:.:.::::::::::::.::........ .       M:::MM: MM:  MM :..::.")
print(" 'M:::.:.:.:.::::::::::::.:.:.:...... . .    ")#:::MM  M: MM MMM ..:..:.")#print("  'M:.:.:.:.:::::::::::::::..:.:........... .    ::MM MM  MM MM::::.:.")
#print("   'M:.:.:.:.:.::::::::::::::.::.:.........  .     ::M MM:MM  MM:.:::::")
#print("    'M:.::::.:.::::::::::::::::..:.:........ . .     MM MM. MM MMMM:::::")
print("     'M:.:.:.:.:.::::::::::::::::.::.:........ .      ")#MM MMM  MM ::::::::")
print("    .::::M..:.:.:.:.::::::::::::::.::.:.......... .    ")#::::MM  MM.::::::.")
print("   .::::::::M:.:.:.:.::::::::::::::::::.::.:....... .     ")#:: M: M.:::.::")
print("   X.X:::::::::::M::.:.:::::::::::::::::::::::.:........   . ")#  ::::::.::'")
print("   'X..X::::::::::::.:::::::::::::::::::::::::::::.......... . ")#::::.::'")
print("     ':X:..X:::::::::::M::::::::::::::::::::::::.::..:...... .  ")#::.::'")  # XXX MODS RIGHT HERE XXX
#print("         '':X....X..X...X.:M::::::::::::::::::::::::::::.....  ..")# :.::")
#print("           :::..X..X...X...:M:::::::::::::::::::::::::::::::.......:'")
#print("          .:::X::::          'm:::::::::::::::::::::::::::::.......M'")
#print("          X::: X:::              ':M::::::::::::::::::::::::::::::::::")
#print("         .:::' :X::                  ':M::::::::::::::::::::::::::::.:.")
#print("         X:::  :X::                     '::MMM::::::::::::::::::::...::.")
#print("        .:::' X::::                          ':MM::::::::::::::::::..:::")
#print("        XX::  X::::                            M:MM::::::::::::::: . M::")
#print("       .:XXX  :X:::                          .M::MM.:::::::::::::.  M::")
#print("       X:XXX:::X:::::::::::::::::::::::::::::M:::M..::::::::::::...:::")
#print("       ::XXXX:::::::::::::::::::::::::::::::M:::M.::::::::::::::::.::")
#print("      .:::XXXX::::                        .M:::M..::::::::::::::::::'")
#print("      X:::' XXX:::                       .M:::M.:::::::::::::::::::/")
#print("      ::::   :X:::                      .M:::M.:::::::::::::::::../")
#print("     .::::  X:::::                      M:::M.:::::::::::::::::../")
#print("     X:::   X::::'                     .M::M.::::::::::::::::::./")
#print("    .::::   :X:::                      M::M.::::::::::::::::...:")
#print("    X::::  .:X:::                     .M:M.:::::::::::::::::.:./")
#print("    ::::'  :::::::::::::::::::::::::::M:M.::.:::::::::::::::.../")
#print("   .::::   :::::::::::::::::::::::::::M:M.:.:::::::::::::::...")
#print("   X::::   :X:::                    .M:M.:::.:::::::::::::.:./")
#print("   :::::  .:X:::                    MMM:.::.:::::::::::::...:")
#print("  .::::'  X:::::                   .M:M.:.::::::::::::::::../")
#print("  X:X::   X::::'                   M:MMM.:.:::::::::::::.../")
#print(" .::XX:   :X:::                   .M:M:.:.:::::::::::::::./")
#print(" X::XX'   :X:::                  .M:MM::.:.::::::::::::../.")
#print(" :::XXX  .:X:::                  M::MM..:.:::::::::::....::")
#print(".::::XX  XX::::           .:M:MM::::MM.:.:.:::::::::::../::.")
#print(":::::XXX X::::'          .:M:MM:::::MM..:.:::::::::::../::::")
#print(":::::'XX :X:::         .M:::M:::::::MM.:.::::::::::::..:::::")
#print("::::: XXX:X:::        .MM:M::M::::::MM..:.:.:::::::::./X::::")
#print(":::::::XX:::::::::::::M:::M:M:::::::MM.:.:.:::::::::./XX::::")
#print(":::::::XX:::::::::::::M:::::::::::::MM..:.:.:::::::..:XX::::.")
#print(":::    :X:::          M:::::::::::::MM.:.:.:.::::::./  ':::::")
#print(":::    :X:::           M::::::::::::MM..:.:.::::::./.   :::::")
#print("::'    :X:::           'M:::::::::::MM.:.:.:::::::::.   :::::")
#print("::    X::::'           .M:::::::::::MM..:.:::::::.:..   :::::")
#print("::    X::::           .M::::::::::::MM...:::::::::/..   :::::.")
#print(":'    :X:::          .M:::::::::::::MM.:.:::::::..:..   'X::::")
#print(":     :X:::         .M::::::::::::::MM   .:::::::/.:.    :::::")
#print(":     :X::::::::::::M::::::::::::::MM    :::  ::: .:::::::::::")
#print(":    .:X::::::::::.M:::::::::::::MM.:      :  :: ..::::::::::::")
#print(".    X::::         M::::::::::::MM.:.:     :  :. .: :..   :::::")
#print(".    X::::         M::::.:.::::MM.: :   :::::::. :. .:..  :::::")
#print("     :X.:         .M:::::::::MMM::::.  :::::: :  :  ....  X::::")
#print("    .:X::        .MMM:::::::MMM::::::::: : :::.  :  .: .  X::::")
#print("    :::::        MMM::::::: MMM:::.:.::   :::.  :/  .::.  :::::.")
#print("    :::::        MMMMMMMM'  MM:::::..::   :::  .:    :..  ':::::")
#print("    :X::         :MMMMMM'   MM::::...     :.  ../    :..   :::::")
#print("   .:XX:         MMMMMMM    'M:::::.:   ::.    :     :..   :::::")
#print("   X::::         MMMMMM'     M::::.:.  ::.    ./     XX:   '::::")
#print("   X:::           'MMM'      '::::::: ::..   ./             ::::.")
#print("   :X::                      .M:::.:. ::.   ::              X::::")
#print("  .:X::                      MM:::::: . ......              :::::")
#print("  X:::'                      MM:::::: :  ::::               '::::")
#print("  X:::                      .MM ::::  .  : ::                ::::.")
#print("  :X::                      MMMM:::  .   :.:                 :::::")
#print(" .:X::                      MM:::::: .    .:                 '::::")
#print(" X:::                       MM:::::: . .::.                   ::::")
#print(" X:::                      .MM ::::  . .. ::                  ::::.")
#print(" :X::                      MMMM:::  .  ..::                   :::::")
#print(".:X::                      MM:::::: .    ::                   '::::")
#print("X:::'                      MM:::::: . ....:                    ::::")
#print("X:::                       MM:MM:: .  ..../                    ::::")
#print("::::                       M..M.M:  ::   :                     ::::.")
#print("::::                       MMM.MM  : :  .'                     '::::")
#print("::::                       MM MM MM :  :                        ::::")
#print("::::                        'MM MM  M  M.                       ::::")
#print("XXXX                          'MM  MM   M                       ::::.")
#print("                                'MMMM  M                        ':::.")
#print("                                 'MMMMM                         ':::.")
#print("                                                                 :::")