print("             =iTTI=i===:===+::=:;;::,;.   .;;:;;;;,:;==+;===;;==+=+, -Tim Park")
print("            ;=ITTT=====+:===;)+==+=+=++:::;++=+====I+:;;++=+=+++ii+:;")
print("            +I)I==+++==;,III=================:+===TITTT=:+;:====IIi;+")
print("             ::I=;;;;+;+=========+==+:::++::==========++i=:.===+T==:+")
print("          ;:)i)+;+;;+=======i===ITT):;;,;:;:,,;===IL==TTT+:=;,;;;;:.:")
print("          ;II++,+;+:=:,i)===T===TTI,;=;:;:.:,:,=IITTI)TTTT=,=;;;;,II=+")
print(" |       ;+)I==::+:=:=)TTT)ITT==LT);::,\:/,:;,:iI=L=iTTTi==);=::+=i)I;")
print(" |__una  ;))++===:==+)TLTLTLL=LI)==)~        ~:=+=+=,=iT====+;+.=+:;):+")
print("          ;==++;,=:=iI=I=i=T===:===)         ;;;.:,.:,+);===+:==,;=I=:")
print(" (Human   ;;;+;;;=;;=======)==;:=;,: /|    |\,::'::..:,;;:++:++=:::+:")
print("  Form:     :;;:;;;;===+:===++ :;:.:| `---'  |:`  :. +.,::;;;::=.;::+")
print(" S Movie)    ;:,:;;;;;;,==:,i  :`':  `-____-' ':  `:    ,:,,;;;::;::+")
print("            ;+=;;;;.::,;;;;'---'-_             -~~~-_   =);:;;;.,.:==++::,")
print("         L;;==+===,.,::::;-~.----.             _.--_ ~- I=:;:;+=iII+==iTTTTIi;")
print(" Ii=ii==;;======+,+.,:::; ,' ##@@ \           / @@# ~-+ |+:;:;==ITTT===TLLLLLT")
print(";;;;:++===Ii===;==.;:._|  | ###  # |         | #  ##  ||T:+;;:===TLLT==)LLLLLL")
print("========TLL)=====,++;| -| : ##@  # |         | #  ## |'|--.++=TL:=)LLLLLLLTLLL")
print("=i==iLLLL)IIL::;:==:;|~\|  \ #### /    |      \ ###  | |  |+==TT:i=LLLLLLLLLLL")
print("TLLLLLLLT=i=)T)==:==+|| `|  ~~~~~~     L       `----' |' ||)+=IT;==)T)T=))LLLT")
print("LLLTLLLIILTLL==:;====`   |                            | //'++==TI:==i========L")
print("LLLII)ILLL)==;=====+;+\o `|           ----           |' /'+:;===II+===========")
print("=i=+:I)L)===;====;;;+;;`\ `|          `--'          .'o/';;;;;====T::=========")
print("=====TT===:====;;+;;;+;|,`-+\                     .'++|;;;+;+;+======+,+======")
print("==;==)====;=+=+;;;;;+;;|;++++`-_                .'++++|:;;;;;;;:==+==++;:===+=")
print("=::=)====;===;;;;+;++;(_):.;++++`-_          _-';i;+;(_);;;;;+;;;+======;;;===")
print("+.+=====+;;;=;;;;++;;+;;.:;;;;+;+;|`-_    _-'|):;;;+;,;);;;;;;;;;;;;+====+;;.+")
print(";:======;;;.+;+;;;+++;+;;;;++;+;++|iii`--'iii|=;;;;;;;;;;;;+;;:;;;;;;;;===;;+.")
print(";.;+====;;;;;,:;;+;+;+;+.---.+;+++|iiiiiiiiii|+;;;;;;;;;;;;:;;;;;:;;;;;;;+;;;;")
print(";::;;;==+;;;;;;,;;;;;;;|     `-.++|iiiiiiiiii|+ ______;;;;;;:;;;:;;;;;;;;;;:;;")
print("+;.;+:;;+;;++;;::++;;+|'_.-----._~~--__ii__----'      |;;;;:;;;;;;;;;;;;;;;;;,")
print("+;:;;;;;;;;;;;;;,;;;;+`--------------/.()_____.------.|:;;;:;;;;;;;;;;;;;;;;,;")
print("+=;;;;;;;;;+;;;::;;+;+;=)=ii+;ii___/  |+=-------------',;;;;;;;:;;;;;;;;;;,.:;")
print("+=:;;;==;;;;;;+;___----------~~~i/'  |'i\   \iii~~--.__;;;;;;;;;;;;;;;;;;:;;;;")
print("+;,;;===___.--~~    ||      . i/'   |'iii\   `\ii.     ||~~~---___;;;;;;:;=+;;")
print("::====./           /++\_.-.__/'    |' ``''\    `\.   __|`|        \._;;;:===;=")
print("=====/        __.--:;+,,,::..`-_   |_______\  ./'__--+:;+++----_     \;:======")
print("====|        /++,;,,,+=.,:++===+-_|HHHHHHHHH\/HH|===+,+,+:..++;;-     \:+=====")
print("===|'       |++++;;   ,,,,,,+==|HHHHHHHHHHHHHHHH|....:...   ;.,==\_    |+=====")
print("===|        |,....:,.:,++,.----'HHHHHHHHHHHHHHH.H|..,,,,...:.+++:::|   `|;====")
print("++|'      ii`,,.+i..,,___/TTTTHHHHHHHHHHHHHHHHHHH`-_---___-_..,++__|    |;====")
print("=+|      iii)\ _+;..-'TTTTTTTTHH.HHHHHHHHHHHHH.HHHHHTTTTTTTT|../iiii    |=====")
print("+|'      iiii|'T`-'TTTTTTTTTTTTHH.HHTTTTTTTTTTTTTHHHTTTTTTTT`-|iiiii    `|;.:+")
print("+|       iiii|TTTTTTTTTTTTTTTTTTHTTTTTTTTTTTT.TTTTTTTTTTTTTTTT|iiiii     |+=;=")
print("|'      iiiiii\TTTTTTTTTTTTTTTTTTT.TTTTTTTTT.TTTTTTTTTTTTTTTT/iiiiii     |:===")
print("        iiiiiii\TTTTTTTTTTTTTTTTTTTHHHHHHHHHHHHTTTTTTTTTTTTT/iiiiiii     `|===")
print("       iiiiiiii|`\TTTTTTTTTTTTTTHHHH.HHHHHH.HHHHHHHTTTTTTT/'|iiiiiiii     |:==")
print("       iiiiiii|':+~\TTTTTTTTTTHHHHHHHHHHHHHHHHHHHHHHHTTT/';+`|iiiiiii     |,++")
print("      iiiiiiii|:;++|TTTTTTTTTHHHHHHHH.HHHH.HHHHHHHHHHHHT|+,;;|iiiiiii     |:+=")
print("      iiiiiii|'++++`|TTTTTTTTHHHHHHHHHHHHHHHHHHHHHHHHHHH|:;+;`|iiiiii     `|:+")
print("     iiiiiii|';+++++`|TTTTTTTHHHHHHHHHH.HHHHHHHHHHHHHHH|'+;;;;|iiiiiii     |;;")
print("     iiiiii|'++;;+;++`|TTTTTTHHHHHH_------_HHHHHHHHHHH|'++;;;;`|iiiiii     |i;")
print("    iiiiii|';+;;;;+;++`|TTTTTTHHH.-    _---=HHHHHHHHH|';++;;;;;`|iiiii     `|;")
print("    iiiii|';+;;;+;;;;++`|TTTTTHH:    .'HHHHHHHHHHHHH|':;;;;;;;;;|iiiii      |;")
print("   iiiiii|:+;;;;;;;;++++|TTTTTHH|    |HHHHHHHHHHHHH.|;++;;++;;;;`|iiiii     |,")
print("   iiiii|'+;+;+;./~\_/~~`|TTTTHH:    `\HHHHH.HHHHHH|\__/~\;+;;;;;|iiiii     |+")
print("  iiiii|';+;___/:;;:;;;;+|TTTTTH`\     ~---=/HHHHHH|:;;;;:\__;;;;`|iiii     `|")
print("  iiii|':;;/+++++,,,,..,,|ITTTTTHH~-.____-~~HHHHHHH|,,....++;~-.;;|iiiii")
print(" iiii|':;;/,,.,.,,,.,,..|IITTTTTHHHHHHHHHHHHHHHHHHHH|,,,++.....|;;`|iiiii")